// <auto-generated />
using System;
using LaptopShopWeb.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaptopShopWeb.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118093427_SeedUserData")]
    partial class SeedUserData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaptopShopWeb.Entity.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop chuyên dụng cho game thủ với cấu hình mạnh mẽ",
                            IsActive = true,
                            Name = "Laptop Gaming",
                            Slug = "laptop-gaming"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop phù hợp cho công việc văn phòng, học tập",
                            IsActive = true,
                            Name = "Laptop Văn Phòng",
                            Slug = "laptop-van-phong"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop dành cho thiết kế đồ họa, render video",
                            IsActive = true,
                            Name = "Laptop Đồ Họa",
                            Slug = "laptop-do-hoa"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop siêu mỏng nhẹ, dễ dàng di chuyển",
                            IsActive = true,
                            Name = "Laptop Mỏng Nhẹ",
                            Slug = "laptop-mong-nhe"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop cao cấp, sang trọng với hiệu năng vượt trội",
                            IsActive = true,
                            Name = "Laptop Cao Cấp",
                            Slug = "laptop-cao-cap"
                        });
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShippingCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ShippingPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderDate");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariantDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CPU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GraphicsCard")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("HasVariants")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RAM")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Screen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Storage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.HasIndex("Price");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "ASUS",
                            CPU = "AMD Ryzen 7 5800H",
                            CategoryId = 1,
                            Color = "Black",
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop gaming ASUS ROG Strix G15 với AMD Ryzen 7, RTX 3060, màn hình 15.6 inch 144Hz",
                            DiscountPrice = 29990000m,
                            GraphicsCard = "NVIDIA RTX 3060 6GB",
                            HasVariants = false,
                            ImageUrl = "/images/products/asus-rog-strix-g15.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "ASUS ROG Strix G15 G513",
                            OperatingSystem = "Windows 11",
                            Price = 32990000m,
                            RAM = "16GB DDR4",
                            Screen = "15.6 inch FHD 144Hz",
                            Slug = "asus-rog-strix-g15-g513",
                            StockQuantity = 15,
                            Storage = "512GB SSD NVMe",
                            ViewCount = 0,
                            Weight = 2.3m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Dell",
                            CPU = "Intel Core i5-1235U",
                            CategoryId = 2,
                            Color = "Silver",
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop Dell Inspiron 15 cho văn phòng với Intel Core i5, thiết kế gọn nhẹ",
                            GraphicsCard = "Intel Iris Xe",
                            HasVariants = false,
                            ImageUrl = "/images/products/dell-inspiron-15.jpg",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Dell Inspiron 15 3520",
                            OperatingSystem = "Windows 11",
                            Price = 15990000m,
                            RAM = "8GB DDR4",
                            Screen = "15.6 inch FHD",
                            Slug = "dell-inspiron-15-3520",
                            StockQuantity = 25,
                            Storage = "256GB SSD",
                            ViewCount = 0,
                            Weight = 1.8m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Apple",
                            CPU = "Apple M3",
                            CategoryId = 5,
                            Color = "Space Gray",
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MacBook Pro 14 inch với chip M3, màn hình Liquid Retina XDR",
                            DiscountPrice = 49990000m,
                            GraphicsCard = "10-core GPU",
                            HasVariants = false,
                            ImageUrl = "/images/products/macbook-pro-14-m3.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "MacBook Pro 14 M3",
                            OperatingSystem = "macOS",
                            Price = 52990000m,
                            RAM = "16GB Unified",
                            Screen = "14.2 inch Liquid Retina XDR",
                            Slug = "macbook-pro-14-m3",
                            StockQuantity = 10,
                            Storage = "512GB SSD",
                            ViewCount = 0,
                            Weight = 1.6m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "MSI",
                            CPU = "Intel Core i7-13700H",
                            CategoryId = 3,
                            Color = "Gray",
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop MSI Creator Z16 dành cho đồ họa với Intel Core i7 và RTX 4060",
                            GraphicsCard = "NVIDIA RTX 4060 8GB",
                            HasVariants = false,
                            ImageUrl = "/images/products/msi-creator-z16.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "MSI Creator Z16",
                            OperatingSystem = "Windows 11 Pro",
                            Price = 45990000m,
                            RAM = "32GB DDR5",
                            Screen = "16 inch QHD+ 165Hz",
                            Slug = "msi-creator-z16",
                            StockQuantity = 8,
                            Storage = "1TB SSD NVMe",
                            ViewCount = 0,
                            Weight = 2.2m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "HP",
                            CPU = "AMD Ryzen 5 7535U",
                            CategoryId = 4,
                            Color = "Pale Gold",
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop HP Pavilion Aero 13 siêu mỏng nhẹ chỉ 1kg với AMD Ryzen 5",
                            DiscountPrice = 17990000m,
                            GraphicsCard = "AMD Radeon",
                            HasVariants = false,
                            ImageUrl = "/images/products/hp-pavilion-aero-13.jpg",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "HP Pavilion Aero 13",
                            OperatingSystem = "Windows 11",
                            Price = 19990000m,
                            RAM = "16GB LPDDR5",
                            Screen = "13.3 inch WUXGA",
                            Slug = "hp-pavilion-aero-13",
                            StockQuantity = 20,
                            Storage = "512GB SSD",
                            ViewCount = 0,
                            Weight = 0.99m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Lenovo",
                            CPU = "AMD Ryzen 7 6800H",
                            CategoryId = 1,
                            Color = "Storm Grey",
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop gaming Lenovo Legion 5 Pro với AMD Ryzen 7 và RTX 3070",
                            DiscountPrice = 35990000m,
                            GraphicsCard = "NVIDIA RTX 3070 8GB",
                            HasVariants = false,
                            ImageUrl = "/images/products/lenovo-legion-5-pro.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Lenovo Legion 5 Pro",
                            OperatingSystem = "Windows 11",
                            Price = 38990000m,
                            RAM = "16GB DDR5",
                            Screen = "16 inch WQXGA 165Hz",
                            Slug = "lenovo-legion-5-pro",
                            StockQuantity = 12,
                            Storage = "512GB SSD",
                            ViewCount = 0,
                            Weight = 2.5m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Acer",
                            CPU = "Intel Core i3-1215U",
                            CategoryId = 2,
                            Color = "Silver",
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptop Acer Aspire 5 với Intel Core i3, phù hợp học sinh sinh viên",
                            GraphicsCard = "Intel UHD",
                            HasVariants = false,
                            ImageUrl = "/images/products/acer-aspire-5.jpg",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Acer Aspire 5 A515",
                            OperatingSystem = "Windows 11",
                            Price = 12990000m,
                            RAM = "8GB DDR4",
                            Screen = "15.6 inch FHD",
                            Slug = "acer-aspire-5-a515",
                            StockQuantity = 30,
                            Storage = "256GB SSD",
                            ViewCount = 0,
                            Weight = 1.7m
                        });
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DiscountPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GraphicsCard")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("RAM")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Storage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsApproved");

                    b.HasIndex("ProductId");

                    b.HasIndex("Rating");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Admin Street",
                            City = "Ho Chi Minh City",
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@laptopshop.com",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$9bIBlTrCHumoYs1INYZ7h.1kMnYBwQtJ.5WBsjfgpK/NxYAEmXMLW",
                            PhoneNumber = "0123456789",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Customer Street",
                            City = "Hanoi",
                            CreatedAt = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@test.com",
                            FullName = "Test Customer",
                            IsActive = true,
                            PasswordHash = "$2a$11$bmGYq9YBj7zcdk9W6ZDXXeQL1RJ3ja4IvkcR9mFlPGb8IsA1LHS5u",
                            PhoneNumber = "0987654321",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Cart", b =>
                {
                    b.HasOne("LaptopShopWeb.Entity.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("LaptopShopWeb.Entity.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.CartItem", b =>
                {
                    b.HasOne("LaptopShopWeb.Entity.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaptopShopWeb.Entity.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaptopShopWeb.Entity.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cart");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Order", b =>
                {
                    b.HasOne("LaptopShopWeb.Entity.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.OrderDetail", b =>
                {
                    b.HasOne("LaptopShopWeb.Entity.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaptopShopWeb.Entity.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LaptopShopWeb.Entity.ProductVariant", "ProductVariant")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductVariantId");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Product", b =>
                {
                    b.HasOne("LaptopShopWeb.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.ProductImage", b =>
                {
                    b.HasOne("LaptopShopWeb.Entity.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.ProductVariant", b =>
                {
                    b.HasOne("LaptopShopWeb.Entity.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Review", b =>
                {
                    b.HasOne("LaptopShopWeb.Entity.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaptopShopWeb.Entity.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("LaptopShopWeb.Entity.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
